### PR TITLE
docs: add env guide

### PR DESCRIPTION
**Pull request by hyomiTheTech**
#### Description of the change\*

Added steps to get environment variables in Readme.md

CLOSES #ISSUENO 

issue#62: [Feat]: Steps to get environment variables

#### Checklist\*

**Please make sure you have done the following:**

- [x] 😄 I've read [CONTRIBUTING.md][contributing] and my PR is up to standards.
- [ ] 🎨 The changes in this PR meet the design plan.
- [x] 🐛 I've tested my PR's source changes for any bugs/render issues.
- [ ] 🧪 I've worked through build failures and tests are passing.
- [x] 📄 I've updated the necessary documentation changes.

#### Notes

Please make sure the steps I wrote are understandable and correct.

Thank you!

[contributing]: https://github.com/web3community/DEV-NFT/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Review by krshdev — APPROVED** [review]

**Comment by hyomiTheTech** [comment]
Oh no, where is these issue coming from ?

**Review by shuklaritvik06 — APPROVED** [review]

**Comment by hyomiTheTech** [comment]
Please ignore these 3 issues. They are line-length issues, and I can't disable these issues. I tried to disable lint by adding disable tag:. But if I do it, it messes up the whole unordered list sequence...

**Review by krshdev — APPROVED** [review]

**Review by KukretiShubham — COMMENTED** [review]
awesome. Thank you

**Comment by hyomiTheTech** [comment]
> awesome. Thank you

Thank You : )

**Pull request merged**
