### PR TITLE
Add: Marketplace beta v0.0.1, collections wip

### PR DESCRIPTION
**Pull request by mkubdev**
#### Description of the change\*

Add: sketchy iteration of the marketplace. Added collections skeleton.

devnft2

#### Notes

* Route not protected at all
* Too much getServerSideProps for the github session

[contributing]: https://github.com/web3community/DEV-NFT/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Comment by mkubdev** [comment]
> ✔️ Deploy Preview for _vigorous-pare-5dd248_ ready!
> 
> 🔨 Explore the source changes: [787bc1a](https://github.com/WebXDAO/DEV-NFT/commit/787bc1a400587c1c94a8dce94048bfabb13fd5d8)
> 
> 🔍 Inspect the deploy log: https://app.netlify.com/sites/vigorous-pare-5dd248/deploys/6229d075cf48600008031c47
> 
> 😎 Browse the preview: https://deploy-preview-89--vigorous-pare-5dd248.netlify.app

Preview can't work due to next-auth redirection url not matching current url.

**Review by krshdev — APPROVED** [review]

**Review by vinzvinci — APPROVED** [review]
Awesome 🔥

**Review by shuklaritvik06 — APPROVED** [review]
LGTM

**Review by KukretiShubham — COMMENTED** [review]
LGTM

**Pull request merged**
