### PR TITLE
Add Explore Section

### PR DESCRIPTION
**Pull request by AbhinavMV**
#### Description of the change\*

Same as #85 
but merging to new-ui instead of main.
Sorry for the trouble.
CLOSES #ISSUENO 

#### Checklist\*

**Please make sure you have done the following:**

- [x] 😄 I've read [CONTRIBUTING.md][contributing] and my PR is up to standards.
- [x] 🎨 The changes in this PR meet the design plan.
- [x] 🐛 I've tested my PR's source changes for any bugs/render issues.
- [ ] 🧪 I've worked through build failures and tests are passing.
- [ ] 📄 I've updated the necessary documentation changes.

#### Notes

[contributing]: https://github.com/web3community/DEV-NFT/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Review by KukretiShubham — APPROVED** [review]

**Review by mkubdev — COMMENTED** [review]
Awesome!

**Review by vinzvinci — COMMENTED** [review]
Looking good 🎉 but I think I may change the new design for `explore section` soon. Maybe we can improve it more on the figma.

**Comment by AbhinavMV** [comment]
Maybe keep it a bit simple this time 😂
The current is really tough to code 🥺

**Comment by vinzvinci** [comment]
Okay noted @AbhinavMV. Thank you for the great contributions 🎉

**Comment by shuklaritvik06** [comment]
> Maybe keep it a bit simple this time joy The current is really tough to code pleading_face

Can understand Abhinav 😅  It would have been indeed a tough task, and you made it 🥳

**Pull request merged**
