### PR TITLE
Add Explore Section

### PR DESCRIPTION
**Pull request by AbhinavMV**
#### Description of the change\*
Mobile view does not look that good yet. 
Will try to figure some other way for this later on.
If you have some suggestions let me know.

Desktop View

image

Ipad View
image

Mobile View
image

CLOSES #ISSUENO 

#### Checklist\*

**Please make sure you have done the following:**

- [x] 😄 I've read [CONTRIBUTING.md][contributing] and my PR is up to standards.
- [x] 🎨 The changes in this PR meet the design plan.
- [x] 🐛 I've tested my PR's source changes for any bugs/render issues.
- [ ] 🧪 I've worked through build failures and tests are passing.
- [ ] 📄 I've updated the necessary documentation changes.

#### Notes

[contributing]: https://github.com/web3community/DEV-NFT/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Review by vinzvinci — APPROVED** [review]
This LGTM 👍

**Review by shuklaritvik06 — APPROVED** [review]
Cool I trust You! Great Work 🎉 🔥

**Review by KukretiShubham — APPROVED** [review]

**Review by krshdev — APPROVED** [review]

**Comment by KukretiShubham** [comment]
closing it then

**Comment by KukretiShubham** [comment]
we already discussed in team-web3 the reason

**Pull request closed without merging**
